### ISSUE TITLE
Mapa mental

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-1-mapa-mental-NoeliaGlez#1]
[mapa mental 1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-NoeliaGlez/files/10693797/mapa.mental.1.pdf)

**Comment by FedericoVictorianoSierra** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
